@startuml
!include C4_Context.puml

LAYOUT_WITH_LEGEND()

title Warmhouse

Person(customer, "User", "Внешний пользователь системы")

System(smart_home_monolith, "Smart Home", "Пользователи могут удалённо просматривать данные со всех умных устройств и управлять ими.")
System_Boundary(house, "Дом") {
    System_Ext(sensor_temperature, "Sensors", "Сенсоры отдельных устройств")
    System_Ext(controller_heat, "Device Controllers", "Регуляторы и контроллеры отдельных устройств")
}

Rel(customer, smart_home_monolith, "Использует")
Rel(sensor_temperature, smart_home_monolith, "Получает данные устройств")
Rel(smart_home_monolith, controller_heat, "Контролирует устройства")

@enduml